version: "3.8"

services:
  app:
    build: ./
    command: ./wait-for-postgres.sh db ./app
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - DB_PASSWORD=postgres

  db:
    restart: always
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5437:5432